// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1qqxDoGUdDyJh2a47WMn-UnHOOdqM3Ag',
    appId: '1:949988819393:web:c669818876d0ce6dc96f40',
    messagingSenderId: '949988819393',
    projectId: 'auction-73143',
    authDomain: 'auction-73143.firebaseapp.com',
    storageBucket: 'auction-73143.appspot.com',
    measurementId: 'G-DZSGJGG5QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZfYs4Xfn3mNN_fjCFiHiIDbn7I_a_TSE',
    appId: '1:949988819393:android:452cebaf48683e0cc96f40',
    messagingSenderId: '949988819393',
    projectId: 'auction-73143',
    storageBucket: 'auction-73143.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj-tmGeVSO2vfe7RHPgStCD-I8Ia_SRdc',
    appId: '1:949988819393:ios:ccac099ff1c8cd97c96f40',
    messagingSenderId: '949988819393',
    projectId: 'auction-73143',
    storageBucket: 'auction-73143.appspot.com',
    iosClientId: '949988819393-iekiuje32ficnbc9o3fl9bn7h5nm1eko.apps.googleusercontent.com',
    iosBundleId: 'com.example.auction',
  );
}
